---
- hosts: somegroup
  remote_user: someuser
  tasks:

    - name: Des-registrando Sistema en Portal de Red Hat
      command: subscription-manager unregister
      register: rhsm-unregister_output
 
    - name: Limpiando datos corruptos 
      command: subscription-manager clean
      register: rhsm-clean_output
      
    - name: Eliminar todas las suscripciones del sistema
      command: subscription-manager remove --all
      register: rhsm-remove-all_output
      
    - name: Registrando Sistema en Portal de Red Hat
      command: subscription-manager register --username someusername --password somepassword
      register: rhsm-register_output

    - name: Agregando pool ID
      command: subscription-manager attach --pool somepoolid
      register: rhsm-attach-pool_output

    - name: Deshabilitando repos
      command: subscription-manager repos --disable=*
      register: disable_output

    - name: Habilitando repo rhel-7-server-rpms
      command: subscription-manager repos --enable rhel-7-server-rpms
      register: enable_output
